#!/usr/bin/env python3
"""
FENG LAB — Daily Literature Fetcher
Searches Semantic Scholar for papers on configured topics.
Writes today's top 6 findings to data/papers.json and appends them to data/archive.json.
Auto-translates titles + abstracts via Gemini API.
"""

import json
import math
import os
import sys
import time
import hashlib
import datetime
import requests
from pathlib import Path

# Windows UTF-8 fix
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

sys.path.insert(0, str(Path(__file__).parent))
from journal_metrics import (  # noqa: E402
    JournalIndex, display_impact, display_tier, impact_value, is_domain_relevant,
)

TODAY = datetime.date.today().isoformat()
DATA_FILE  = Path(__file__).parent.parent / "data" / "papers.json"
ARCHIVE_FILE = Path(__file__).parent.parent / "data" / "archive.json"
DAILY_LIMIT = 6

# ── Journal quality gate ─────────────────────────────────────────────────────
# Metrics come from data/journals.json, regenerated by
# scripts/update_journal_metrics.py from OpenAlex + the curated data/jcr_seed.json.
#
# This replaced a hardcoded dict that matched venues by loose substring, which
# had two consequences: "International Journal of Sports Medicine" inherited
# "Sports Medicine"'s IF of 9.8 (39 of 190 archived papers carried that wrong
# number), and any journal absent from the dict was silently discarded.
JOURNALS = JournalIndex.load()

MIN_IF = 3.0            # curated JCR floor
MIN_OPENALEX_2YR = 2.0  # OpenAlex runs lower than JCR, so it gets its own floor


def _always_include() -> set[str]:
    """Journals the lab wants regardless of what the thresholds say.

    Editorial preference, kept separate from the metric gate so the two do not
    get confused. Gait & Posture sits here: IF 2.7 and JCR Q2, but it is a core
    venue for this lab's biomechanics work.
    """
    seed = Path(__file__).parent.parent / "data" / "jcr_seed.json"
    if not seed.exists():
        return set()
    try:
        payload = json.loads(seed.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()
    from journal_metrics import normalize_name
    return {normalize_name(n) for n in payload.get("always_include", []) if n}


ALWAYS_INCLUDE = _always_include()
_RESOLVED_LIVE = []   # journals discovered this run, persisted at the end
_UNRESOLVED = set()   # venues that failed this run; do not retry within the run

# A run screens up to ~270 candidates and most rejected venues are conference
# proceedings or predatory titles that no source will ever resolve. Without a
# ceiling, one bad day of results could spend a large slice of the easyScholar
# daily quota on journals that will never be published.
MAX_LIVE_LOOKUPS = 25


def _passes_gate(entry: dict) -> bool:
    """Is this journal good enough for the digest?

    Any one of these is enough — a journal can be excellent in its own field
    while sitting below the sport-science impact floor:
      * impact factor >= MIN_IF
      * JCR or SJR quartile Q1
      * CAS (中科院) tier 1区 or 2区 in any sub-category
      * on the always-include list
      * failing all of the above, a fallback citation metric above the floor
    """
    from journal_metrics import normalize_name

    if entry.get("is_preprint_server"):
        return False  # a preprint server reached a journal query; not a journal
    if normalize_name(entry.get("name", "")) in ALWAYS_INCLUDE:
        return True

    try:
        if float(entry.get("jcr_if") or 0) >= MIN_IF:
            return True
    except (TypeError, ValueError):
        pass

    if "Q1" in (entry.get("jcr_quartile") or "", entry.get("sjr_quartile") or ""):
        return True

    cas = f"{entry.get('cas_tier_small') or ''} {entry.get('cas_tier') or ''}"
    if "1区" in cas or "2区" in cas:
        return True

    if not entry.get("jcr_if"):
        # This is the weakest tier: no impact factor, no quartile, no CAS tier —
        # only a citation rate. A citation rate says nothing about subject, and
        # Photonics (OpenAlex 2yr 2.2) cleared it into a sports-science digest.
        # Journals reaching this branch must also be placeable in the field.
        if not is_domain_relevant(entry):
            return False
        for field, floor in (("cite_doc_2y", MIN_IF), ("openalex_2yr", MIN_OPENALEX_2YR)):
            try:
                if float(entry.get(field) or 0) >= floor:
                    return True
            except (TypeError, ValueError):
                continue
    return False


def lookup_journal(venue: str, issns=()):
    """Resolve a venue to (entry, if_display, if_source, passes_gate).

    On a cache miss the journal is resolved live rather than discarded. The old
    lookup treated "not in my hardcoded dict" as "not Q1", so the digest could
    never surface a paper from Nature, The Lancet or J Physiol no matter how
    good it was.
    """
    entry = JOURNALS.lookup(venue, issns)

    if not entry and venue:
        from journal_metrics import normalize_name
        key = normalize_name(venue)
        # Skip venues already tried and skip further lookups once the budget is
        # spent — otherwise the same unresolvable venue is re-queried on every
        # candidate that carries it, and again tomorrow.
        # Budget counts attempts, not successes: a failed lookup costs the same
        # API calls as a successful one, and the first full-pool run spent 40
        # lookups against a stated cap of 25 because only the hits were counted.
        if (key in _UNRESOLVED
                or JOURNALS.is_unresolved(venue)
                or len(_RESOLVED_LIVE) + len(_UNRESOLVED) >= MAX_LIVE_LOOKUPS):
            return None, "", "", False
        try:
            from update_journal_metrics import resolve_live
            entry = resolve_live(venue, list(issns))
        except Exception as e:                       # noqa: BLE001
            print(f"    [!] live lookup failed for '{venue[:40]}': {e}")
            entry = None
        if entry:
            JOURNALS.add(entry)
            _RESOLVED_LIVE.append(entry["name"])
            print(f"    + resolved new journal: {entry['name'][:50]}")
        else:
            _UNRESOLVED.add(key)
            JOURNALS.mark_unresolved(venue)

    if not entry:
        return None, "", "", False

    if_display, if_source = display_impact(entry)
    return entry, if_display, if_source, _passes_gate(entry)

# ── Search topics ─────────────────────────────────────────────────────────────
# Queries include journal names to bias Semantic Scholar toward Q1 sources.
# Non-preprint results are further filtered by Q1_JOURNALS + MIN_IF at runtime.
SEARCHES = {
    "biomechanics": [
        "gait biomechanics sports injury lower limb Journal of Biomechanics",
        "IMU inertial measurement unit running biomechanics Journal of Sports Sciences",
        "electromyography muscle activation sports biomechanics Medicine Science Sports Exercise",
        "plantar pressure foot mechanics gait running British Journal of Sports Medicine",
        "motion capture movement analysis sports injury Scandinavian Journal Medicine Science Sports",
    ],
    "performance": [
        "rate of force development neuromuscular athletic performance Medicine Science Sports Exercise",
        "sprint jump strength power training Sports Medicine",
        "running economy fatigue resistance training Journal Strength Conditioning Research",
        "high intensity interval training sport performance International Journal Sports Physiology",
        "aerobic capacity VO2max endurance athletes Scandinavian Journal Medicine Science Sports",
    ],
    "supplements": [
        "creatine caffeine sports supplement randomized controlled trial Journal Strength Conditioning",
        "ergogenic aids sports nutrition randomized trial Medicine Science Sports Exercise",
        "nitrate beta-alanine sport performance supplementation International Journal Sport Nutrition",
        "protein intake muscle recovery resistance exercise European Journal Applied Physiology",
        "collagen peptide joint recovery tendon supplement British Journal Sports Medicine",
    ],
    "preprint": [
        # Preprints are exempt from Q1/IF filter — search bioRxiv/medRxiv
        "sports biomechanics running gait injury bioRxiv preprint",
        "exercise performance neuromuscular training medRxiv preprint",
        "wearable sensor IMU motion analysis sports preprint",
    ],
}

SS_URL    = "https://api.semanticscholar.org/graph/v1/paper/search"
SS_FIELDS = (
    "title,authors,year,abstract,externalIds,publicationDate,"
    "venue,publicationVenue,publicationTypes,tldr,"
    "isOpenAccess,openAccessPdf,citationCount"
)
# Without a key, Semantic Scholar's search endpoint shares one pool across all
# anonymous callers and returns 429 often enough to silently empty a daily run.
SS_API_KEY = os.environ.get("SEMANTIC_SCHOLAR_API_KEY", "")


# Measured 2026-07-29: with a key, 2 of 8 search calls spaced 3s apart still
# returned 429 — well short of the documented 1 rps, so the endpoint is simply
# flaky. Without a key it was 0 of 8. More attempts, with the delay capped so a
# bad run cannot stretch the job indefinitely.
SS_TRIES = 6
SS_MAX_DELAY = 15.0


def ss_get(params: dict, tries: int = SS_TRIES):
    """GET the search endpoint with capped exponential backoff on 429/5xx."""
    headers = {"x-api-key": SS_API_KEY} if SS_API_KEY else {}
    delay = 2.0
    for attempt in range(tries):
        try:
            r = requests.get(SS_URL, params=params, headers=headers, timeout=25)
            if r.status_code == 429 or r.status_code >= 500:
                if attempt == tries - 1:
                    print(f"    [!] giving up after {tries} tries (HTTP {r.status_code})")
                    return None
                print(f"    ... HTTP {r.status_code}, retrying in {delay:.0f}s")
                time.sleep(delay)
                delay = min(delay * 2, SS_MAX_DELAY)
                continue
            r.raise_for_status()
            return r.json()
        except requests.RequestException as e:
            if attempt == tries - 1:
                print(f"    [!] request failed: {e}")
                return None
            time.sleep(delay)
            delay = min(delay * 2, SS_MAX_DELAY)
    return None

# ── Fetch ─────────────────────────────────────────────────────────────────────
def fetch_ss(query: str, category: str, limit: int = 10) -> list:
    """Fetch papers from Semantic Scholar.
    For non-preprint categories, only papers from JCR Q1 journals (IF >= MIN_IF)
    are kept.  Preprint papers are passed through without journal filtering.
    """
    papers = []
    is_preprint = (category == "preprint")

    data = ss_get({
        "query": query,
        "fields": SS_FIELDS,
        "limit": limit,
        "publicationDateOrYear": f"{datetime.date.today().year - 3}:",
    })
    if data is None:
        return papers

    accepted = rejected_if = rejected_abs = 0

    for p in data.get("data", []):
        title    = (p.get("title") or "").strip()
        abstract = (p.get("abstract") or "").strip()
        if not title or not abstract or len(abstract) < 80:
            rejected_abs += 1
            continue

        pv = p.get("publicationVenue") or {}
        venue = (pv.get("name") or p.get("venue") or "").strip()
        issns = pv.get("issn") or []
        if isinstance(issns, str):
            issns = [issns]

        entry, if_val, if_source, passes = lookup_journal(venue, issns)

        if is_preprint:
            # Only keep things that really are preprints, so this category stops
            # acting as a bypass for journals that failed the quality gate.
            if not _looks_like_preprint(p, entry, venue):
                rejected_if += 1
                continue
        elif not passes:
            rejected_if += 1
            continue

        doi      = p.get("externalIds", {}).get("DOI", "")
        authors  = [a.get("name", "") for a in (p.get("authors") or [])[:5]]
        is_oa    = bool(p.get("isOpenAccess"))
        oa_pdf   = p.get("openAccessPdf") or {}
        pdf_url  = oa_pdf.get("url", "") if isinstance(oa_pdf, dict) else ""
        citations = p.get("citationCount") or 0
        tldr     = (p.get("tldr") or {}).get("text", "") if isinstance(p.get("tldr"), dict) else ""

        papers.append({
            "id": hashlib.md5((title + str(p.get("year", ""))).encode()).hexdigest()[:8],
            "title_en":       title,
            "title_zh":       "",
            "authors":        authors,
            "journal":        entry.get("name") if entry else venue,
            "journal_issn":   (entry.get("issn") or [""])[0] if entry else "",
            "year":           (p.get("year") or datetime.date.today().year),
            "date_added":     TODAY,
            "category":       category,
            "doi":            doi,
            "impact_factor":  if_val,
            "if_source":      if_source,
            "journal_tier":   display_tier(entry),
            "evidence":       _evidence_level(p),
            "citation_count": citations,
            "is_open_access": is_oa,
            "pdf_url":        pdf_url,
            "tldr_en":        tldr,
            "tldr_zh":        "",
            "abstract_en":    abstract[:900],
            "abstract_zh":    "",
            "keywords":       [],
        })
        accepted += 1

    print(f"    accepted={accepted}, rejected(journal gate)={rejected_if}, rejected(no abs)={rejected_abs}")
    time.sleep(1.2 if SS_API_KEY else 3.0)
    return papers


def _looks_like_preprint(paper: dict, entry: dict | None, venue: str) -> bool:
    if entry and entry.get("is_preprint_server"):
        return True
    doi = (paper.get("externalIds") or {}).get("DOI", "") or ""
    if doi.startswith("10.1101/") or doi.startswith("10.51224/"):  # bioRxiv/medRxiv, SportRxiv
        return True
    if (paper.get("externalIds") or {}).get("ArXiv"):
        return True
    return any(k in venue.lower() for k in ("biorxiv", "medrxiv", "sportrxiv", "arxiv", "preprint"))


# Sports-science readers filter on study design before anything else, so surface
# it as a first-class field rather than making them read the abstract to find it.
_EVIDENCE_ORDER = [
    ("MetaAnalysis",   "meta"),
    ("Review",         "review"),
    ("ClinicalTrial",  "trial"),
]


def _evidence_level(paper: dict) -> str:
    types = paper.get("publicationTypes") or []
    for ss_type, label in _EVIDENCE_ORDER:
        if ss_type in types:
            return label
    return ""


# ── Deduplication ─────────────────────────────────────────────────────────────
def dedupe(papers: list) -> list:
    seen, result = set(), []
    for p in papers:
        key = (p.get("doi") or "").strip() or p.get("title_en", "").lower()[:60]
        if key and key not in seen:
            seen.add(key)
            result.append(p)
    return result


def impact_factor_value(paper: dict) -> float:
    try:
        return float(paper.get("impact_factor") or 0)
    except (TypeError, ValueError):
        return 0.0


def paper_score(paper: dict, today: datetime.date | None = None) -> float:
    """Rank papers for a *daily* digest.

    Sorting by raw citation count — the previous behaviour — structurally
    favours the oldest paper in the window, because citations only accumulate.
    A 2023 paper with 40 citations always outranked anything published this
    month, so the "daily digest" mostly resurfaced three-year-old work.

    Citations are therefore divided by the paper's age to get a citation *rate*,
    and a recency bonus keeps genuinely new work visible before it has had time
    to be cited at all.
    """
    today = today or datetime.date.today()
    year = paper.get("year") or today.year
    age = max(today.year - int(year) + 0.5, 0.5)   # 0.5 for the current year

    citations = paper.get("citation_count") or 0
    citation_rate = citations / age

    impact = impact_factor_value(paper)

    # Diminishing returns: the gap between 0 and 10 citations/year matters far
    # more than the gap between 90 and 100.
    def damp(x: float) -> float:
        return math.log1p(max(x, 0))

    recency_bonus = {0: 3.0, 1: 1.5, 2: 0.5}.get(today.year - int(year), 0.0)
    # Meta-analyses and systematic reviews carry more weight per paper than a
    # single trial, which is how this audience reads a digest.
    evidence_bonus = {"meta": 1.2, "review": 0.8, "trial": 0.5}.get(
        paper.get("evidence") or "", 0.0)

    return (2.0 * damp(citation_rate)
            + 1.0 * damp(impact)
            + recency_bonus
            + evidence_bonus)


RECENT_WINDOW_DAYS = 30


def recently_published(archive_file: Path = ARCHIVE_FILE,
                       days: int = RECENT_WINDOW_DAYS,
                       today: datetime.date | None = None) -> set:
    """Keys (DOI or id) published in the last `days` days.

    The fetcher had no memory of what it had already shown, and the same query
    returns the same top-ranked papers day after day, so the digest repeated
    itself: 190 archived entries covered only 66 distinct papers, some appearing
    seven times. A reader checking daily mostly saw yesterday's list again.
    """
    if not archive_file.exists():
        return set()
    try:
        archive = json.loads(archive_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()

    today = today or datetime.date.today()
    cutoff = (today - datetime.timedelta(days=days)).isoformat()

    seen = set()
    for date, papers in (archive.get("dates") or {}).items():
        if date < cutoff:
            continue
        for p in papers:
            doi = (p.get("doi") or "").strip().lower()
            if doi:
                seen.add(doi)
            if p.get("id"):
                seen.add(p["id"])
    return seen


def select_top_daily_papers(papers: list, limit: int = DAILY_LIMIT,
                            exclude: set | None = None) -> list:
    """Select the best papers across all categories, skipping recent repeats.

    If filtering leaves too few papers, the excluded ones are added back rather
    than shipping a near-empty digest — a repeat beats an empty page.
    """
    unique = dedupe(papers)
    exclude = exclude if exclude is not None else recently_published()

    def key_of(p):
        return (p.get("doi") or "").strip().lower() or p.get("id") or ""

    fresh = [p for p in unique if key_of(p) not in exclude]
    ranked = sorted(fresh, key=paper_score, reverse=True)

    if len(ranked) < limit:
        repeats = sorted((p for p in unique if key_of(p) in exclude),
                         key=paper_score, reverse=True)
        skipped = len(unique) - len(fresh)
        if repeats:
            print(f"  [i] Only {len(ranked)} fresh papers; backfilling from "
                  f"{skipped} recently-shown ones.")
        ranked += repeats

    return ranked[:limit]


def write_daily_outputs(papers: list, data_file: Path = DATA_FILE, archive_file: Path = ARCHIVE_FILE, today=None) -> None:
    date_str = (today or datetime.date.today()).isoformat()
    today_papers = []
    for paper in papers:
        item = dict(paper)
        item["date_added"] = date_str
        today_papers.append(item)

    data_file.parent.mkdir(parents=True, exist_ok=True)
    with open(data_file, "w", encoding="utf-8") as f:
        json.dump({"last_updated": date_str, "papers": today_papers}, f, ensure_ascii=False, indent=2)

    archive = {"last_updated": date_str, "dates": {}}
    if archive_file.exists():
        with open(archive_file, "r", encoding="utf-8") as f:
            archive = json.load(f)
        archive.setdefault("dates", {})

    archive["last_updated"] = date_str
    archive["dates"][date_str] = today_papers
    with open(archive_file, "w", encoding="utf-8") as f:
        json.dump(archive, f, ensure_ascii=False, indent=2)


# ── Gemini translation ────────────────────────────────────────────────────────
def translate_papers(papers: list) -> list:
    """Fill title_zh and abstract_zh for papers missing translations."""
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        print("  [!] GEMINI_API_KEY not set, skipping translation.")
        return papers

    to_translate = [p for p in papers if not p.get("title_zh") or not p.get("abstract_zh")]
    if not to_translate:
        print(f"  All papers already have translations.")
        return papers

    print(f"  Translating {len(to_translate)} papers via Gemini...")

    # Process in batches of 6 to stay within token limits
    BATCH = 6
    for start in range(0, len(to_translate), BATCH):
        batch = to_translate[start:start + BATCH]
        items = "\n\n".join([
            f"{i+1}. Title: {p['title_en']}\nAbstract: {p['abstract_en'][:600]}"
            for i, p in enumerate(batch)
        ])
        prompt = (
            f"Translate the following {len(batch)} academic paper titles and abstracts "
            f"into Chinese. Return ONLY a JSON array with {len(batch)} objects, "
            f'each with "title_zh" and "abstract_zh" fields. '
            f"Keep translations accurate and academic.\n\n{items}"
        )
        try:
            import google.generativeai as genai
            genai.configure(api_key=api_key)
            model = genai.GenerativeModel("gemini-2.5-flash")
            resp = model.generate_content(prompt)
            raw = resp.text.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            translations = json.loads(raw.strip())
            for i, p in enumerate(batch):
                if i < len(translations):
                    p["title_zh"]    = translations[i].get("title_zh", "")
                    p["abstract_zh"] = translations[i].get("abstract_zh", "")
            print(f"    Batch {start//BATCH + 1}: {len(batch)} translated ✓")
        except Exception as e:
            print(f"    [!] Translation batch error: {e}")
        time.sleep(2)

    return papers


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print(f"FENG LAB — Daily fetch  [{TODAY}]")

    # Fetch new papers
    # Use larger per-query limit (15) because Q1 filtering discards many results
    new_papers = []
    for category, queries in SEARCHES.items():
        print(f"\n▸ {category} (Q1/IF≥{MIN_IF} filter: {'off' if category == 'preprint' else 'on'})")
        for q in queries:
            print(f"  query: {q[:65]}...")
            fetched = fetch_ss(q, category, limit=15)
            new_papers.extend(fetched)

    print(f"\nNew papers collected: {len(new_papers)}")
    selected_papers = select_top_daily_papers(new_papers)
    print(f"Top papers selected: {len(selected_papers)}")

    # Translate new papers that are missing translations
    selected_papers = translate_papers(selected_papers)
    write_daily_outputs(selected_papers)

    # Persist journals discovered during this run so the next one starts warm
    # and the metrics cache grows with the site instead of being capped.
    if _RESOLVED_LIVE or _UNRESOLVED:
        JOURNALS.save()
        if _RESOLVED_LIVE:
            print(f"\n  Cached {len(_RESOLVED_LIVE)} newly-resolved journals: "
                  f"{', '.join(_RESOLVED_LIVE[:5])}"
                  f"{' …' if len(_RESOLVED_LIVE) > 5 else ''}")
        if _UNRESOLVED:
            print(f"  Remembered {len(_UNRESOLVED)} unresolvable venues "
                  f"so they are not re-queried tomorrow.")

    print(f"\n✓ Done. Today's papers: {len(selected_papers)}")


if __name__ == "__main__":
    main()
